<?php

/**
 * PluginsfShortUrlBannedDomain
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginsfShortUrlBannedDomain extends BasesfShortUrlBannedDomain
{
  public function cleanShortUrls()
  {
    $regex = '^(http|https|ftp|ftps)://('.$this->getDomain().')(:[0-9]+)?(/|/.*)?$';
    Doctrine_Query::create()
      ->delete()
      ->from('sfShortUrl u')
      ->where('u.longurl REGEXP ?', $regex)
      ->execute();
  }
}