<?php
/**
 * PluginsfShortUrlTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfDoctrineShortUrlPlugin
 * @subpackage model
 * @author     Xavier Lacot <xavier@lacot.org>
 */
class PluginsfShortUrlTable extends Doctrine_Table
{
  /**
   * Generates a short url
   */
  public function acceptOrCreateSfShortUrl($shorturl = null)
  {
    $acceptable = false;

    while (!$acceptable)
    {
      if ($shorturl)
      {
        $acceptable = (count($this->findByShorturl($shorturl)) == 0);
      }

      if (!$acceptable)
      {
        $shorturl = substr(md5(microtime()), 0, 5);
      }
    }

    return $shorturl;
  }

  public function generate($longurl, $shorturl = '')
  {
    if ('' == $shorturl)
    {
      // try to retrieve a corresponding url within the public ones
      $shorturl_object = $this->findOneByLongurl($longurl);
    }
    else
    {
      // try to retrieve a corresponding couple (shorturl, longurl)
      $objects = Doctrine_Query::create()
        ->from('sfShortUrl u')
        ->where('u.longurl = ?', $longurl)
        ->andWhere('u.shorturl = ?', $shorturl)
        ->execute();
      $shorturl_object = isset($objects[0]) ? $objects[0] : null;
    }

    if (!isset($shorturl_object) || !$shorturl_object)
    {
      // no acceptable object => create one
      $shorturl = $this->acceptOrCreateSfShortUrl($shorturl);
      $shorturl_object = new sfShortUrl();
      $shorturl_object->setLongurl($longurl);
      $shorturl_object->setShorturl($shorturl);
      $shorturl_object->setIsEnabled(true);
      $shorturl_object->setViewcount(0);
      $shorturl_object->save();
    }

    return $shorturl_object;
  }
}