<?php

/**
 * PluginsfShortUrlBannedDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfShortUrlBannedDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfShortUrlBannedDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfShortUrlBannedDomain');
    }
}