<?php

/**
 * PluginsfShortUrl
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    sfDoctrineShortUrlPlugin
 * @subpackage model
 * @author     Xavier Lacot <xavier@lacot.org>
 */
abstract class PluginsfShortUrl extends BasesfShortUrl
{

}