sfShortUrl:
  actAs: [Timestampable]
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    shorturl:         { type: varchar, size: 255, unique: true }
    longurl:          { type: clob }
    viewcount:        { type: integer, default: 0 }
    last_visited_at:  { type: timestamp }
    is_malware:       { type: boolean, default: false }
    is_enabled:       { type: boolean, default: true }
    is_external:      { type: boolean, default: false }
  indexes:
    uriindex:
      fields:
        longurl:
          length:          "255"
    shorturlindex:
      fields:         [shorturl]
      type:           unique

sfShortUrlBannedDomain:
  actAs: [Timestampable]
  columns:
    id:               { type: integer, primary: true, autoincrement: true }
    domain:           { type: varchar, size: 255, unique: true }
  indexes:
    domainindex:
      fields:         [domain]
      type:           unique